title: "azming.com 文章记录基地"
theme: jekyll-theme-midnight

nav:
- name: Home
  link: /
- name: About
  link: /about.md
  
<nav>
  {% for item in site.nav %}
    <a href="{{ item.link }}" 
      {% if page.url == item.link %} style="color: red;" {% endif %}
    >
      {{ item.name }}
    </a>
  {% endfor %}
</nav>
